#!/bin/bash
# Install helm

curl -o get_helm.sh https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
chmod +x get_helm.sh
./get_helm.sh

# Installing Tiller with RBAC enabled

kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

# Installing Tiller without RBAC

helm init

# Install Helm without Tiller

helm init --client-only

# Fetch and untar some chart

helm fetch somechart --untar

# Render template

helm template somechart -x somechart/templates/deployment.yaml somedir/deployment.yaml

